<?php
// @codingStandardsIgnoreFile
?>
<?php if ($this->isEnabled()) : ?>
    <?php $dataLayerObject = $this->getDataLayerAsJson(); ?>
    <script>
        window.getWpGA4Cookie = function(name) {
            match = document.cookie.match(new RegExp(name + '=([^;]+)'));
            if (match) return decodeURIComponent(match[1].replace(/\+/g, ' ')) ;
        };

        window.dataLayer = window.dataLayer || [];
        <?php if ($dataLayerObject != '[[]]') : ?>
        var dl4Objects = <?php echo $dataLayerObject; ?>;
        for (var i in dl4Objects) {
            window.dataLayer.push(dl4Objects[i]);
        }
        <?php endif; ?>
        var wpGA4Cookies = [<?php echo $this->getWpGA4CookiesForJs(); ?>];
        wpGA4Cookies.map(function(cookieName) {
            var cookieValue = window.getWpGA4Cookie(cookieName);
            if (cookieValue) {
                var dl4Object = {};
                dl4Object[cookieName.replace('wp_ga4_', '')] = cookieValue;
                window.dataLayer.push(dl4Object);
            }
        });
    </script>
<?php endif; ?>
