<?php
// @codingStandardsIgnoreFile
?>
<?php if($this->isEnabled()) : ?>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php $helper = $this->helper('WeltPixel\GA4\Helper\Data'); ?>
    <?php if (count($productCollection)) : ?>
        <?php $categoryProducts = array(); ?>
        <?php $listValue = ($block->getListPrefix()) ? $block->getListPrefix() . ' ' . __('Search Result') : __('Search Result'); ?>
        <?php $i = 1; ?>
        <?php foreach($productCollection as $product) : ?>
            <?php $categoryProduct = []; ?>
            <?php $categoryProduct['item_name'] = html_entity_decode($product->getName()); ?>
            <?php $categoryProduct['item_id'] = $helper->getGtmProductId($product); ?>
            <?php $categoryProduct['price'] = number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', ''); ?>
            <?php if ($helper->isBrandEnabled()) : ?>
                <?php $categoryProduct['item_brand'] = $helper->getGtmBrand($product); ?>
            <?php endif;?>
            <?php $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($product->getCategoryIds()); ?>
            <?php $categoryProduct = array_merge($categoryProduct, $ga4Categories); ?>
            <?php $categoryProduct['item_list_name'] = $listValue; ?>
            <?php $categoryProduct['item_list_id'] =  str_replace(' ', '_', strtolower($listValue)); ?>
            <?php $categoryProduct['index'] = $i; ?>
            <?php $categoryProduct['currency'] = $this->getCurrencyCode(); ?>
            <?php $categoryProducts[] = $categoryProduct; ?>
            <?php $i++ ; ?>
        <?php endforeach; ?>
        <?php $this->setEcommerceData('items', $categoryProducts); ?>
        <?php $this->setDataLayerOption('event', 'view_item_list'); ?>
    <?php endif; ?>

    <?php if ($helper->isAdWordsRemarketingEnabled()): ?>
        <?php
        $remarketingData = [];
        $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_SEARCHRESULTS;
        ?>
        <?php $this->setDataLayerOption('google_tag_params', $remarketingData); ?>
    <?php endif; ?>

<?php endif; ?>
