<table autosize="2" class="gallery">
    <?php
    $i = 0;
    foreach($this->getMediaGalleryImagesWithMainImage() as $image){ ?>
        <?php if($i % 2 == 0){ ?>
            <tr>
        <?php } ?>
                <td class="centerimage">
                    <img class="img-responsive" src="<?php echo $image->getUrl(); ?>" />
                </td>
        <?php if($i % 2 == 1 || $i == ($this->getImageCount())){ ?>
            </tr>
        <?php }
        $i++;
    } ?>
</table>
