<style>
    a {
      color: #da2020;
    }
    a:hover {
      color: #d6f300;
    }
    .wrap > h1 {
      margin: 26px auto;
    }
    #showcase {
      height: 460px;
      background: #16235e;
      background: -moz-linear-gradient(top, #16235e 0%, #020223 100%); /* FF3.6+ */
      background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#16235e), color-stop(100%,#020223)); /* Chrome, Safari4+ */
      background: -webkit-linear-gradient(top, #16235e 0%, #020223 100%); /* Chrome10+, Safari5.1+ */
      background: -o-linear-gradient(top, #16235e 0%, #020223 100%); /* Opera 11.10+ */
      background: -ms-linear-gradient(top, #16235e 0%, #020223 100%); /* IE10+ */
      background: linear-gradient(to bottom, #16235e 0%, #020223 100%); /* W3C */
      -webkit-box-shadow: 0px 0px 13px 5px #DB1242;
      -moz-box-shadow: 0px 0px 13px 5px #DB1242;
      box-shadow: 0px 0px 13px 5px #DB1242;
      -webkit-border-radius: 8px;
      -moz-border-radius: 8px;
      border-radius: 8px;
    }
    #item-title {
      color: #F31414;
      font-size: 29px;
      letter-spacing: 0.13em;
      text-shadow: 1px 1px 6px #C72B2B;
      text-align: center;
      margin-top: 30px;
      margin-bottom: 22px;
    }
    #nav {
      text-align: center;
    }
    #nav > button {
      width: 64px;
      height: 36px;
      color: #666;
      font: bold 16px arial;
      text-align: center;
      margin: 5px;
      text-shadow: 0px 1px 0px #f5f5f5;
      background: #f6f6f6;
      border: solid 2px rgba(0, 0, 0, 0.4);
      -webkit-border-radius: 5px;
      -moz-border-radius: 5px;
      border-radius: 5px;
      -webkit-box-shadow: 0 0 9px 1px rgba(0, 0, 0, 0.4);
      -moz-box-shadow: 0 0 9px 1px rgba(0, 0, 0, 0.4);
      box-shadow: 0 0 9px 1px rgba(0, 0, 0, 0.4);
      cursor: pointer;
    }
    #nav > button:active,
    #nav > button.down {
      background: #dfdfdf;
      border: solid 2px rgba(0, 0, 0, 0.6);
      box-shadow: none;
    }
    #share {
      top: -9px;
    }
    #credits {
      top: -15px;
    }
  </style>
<?php 
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $block = $objectManager->create('FME\Photogallery\Block\PList');
  $helper = $objectManager->create('FME\Photogallery\Helper\Data');
  $collection=$block->getAllPhotoGalleryImages();
?>
<div class="wrap">
  <div id="showcase" class="noselect" style="position: relative; overflow: hidden; visibility: visible;">
    <?php
        foreach ($collection as $_item):
    ?> 
      <div class="cloud9-item" title="" style="position: absolute; width: 297px; height: 355px; overflow: hidden; transform-origin: 0px 0px; z-index: 99; transform: translate(343.488px, 89.9993px) scale(0.999997);"><img class="reflected" src="<?php echo $helper->getMediaUrl($_item["img_name"]); ?>" alt="Wyzo" style="display: block; border: 0px; width: 100%;"><canvas width="297" height="59" style="display: block; border: 0px; margin-top: 12px; width: 100%;"></canvas></div>
      
    <?php
      endforeach;
    ?>
  </div>
  <footer>
    <p id="item-title"></p>
      <div id="nav" class="noselect">
        <button class="left">
          ←
        </button>
        <button class="right">
          →
        </button>
      </div>
  </footer>
</div>
<script>
  require(['jquery','cloud9'], function($){
    $(function() {
      var showcase = $("#showcase"), title = $('#item-title')
      showcase.Cloud9Carousel( {
        yOrigin: 42,
        yRadius: 48,
        mirror: {
          gap: 12,
          height: 0.2
        },
        buttonLeft: $("#nav > .left"),
        buttonRight: $("#nav > .right"),
        autoPlay: 1,
        bringToFront: true,
        onRendered: rendered,
        onLoaded: function() {
          showcase.css( 'visibility', 'visible' )
          showcase.css( 'display', 'none' )
          showcase.fadeIn( 1500 )
        }
      })
      function rendered( carousel ) {
        title.text( carousel.nearestItem().element.alt )
        var c = Math.cos((carousel.floatIndex() % 1) * 2 * Math.PI)
        title.css('opacity', 0.5 + (0.5 * c))
      }
      $('#nav > button').click( function( e ) {
        var b = $(e.target).addClass( 'down' )
        setTimeout( function() { b.removeClass( 'down' ) }, 80 )
      })
      $(document).keydown( function( e ) {
        switch( e.keyCode ) {
          /* left arrow */
          case 37:
            $('#nav > .left').click()
            break

          /* right arrow */
          case 39:
            $('#nav > .right').click()
        }
      })
    });
  });
</script>
