<?php
/**
 * Magezon
 *
 * This source file is subject to the Magezon Software License, which is available at https://www.magezon.com/license
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to https://www.magezon.com for more information.
 *
 * @category  Magezon
 * @package   Magezon_Builder
 * @copyright Copyright (C) 2019 Magezon (https://www.magezon.com)
 */

namespace Magezon\Builder\Model\Source;

class OpenIconic
{
	public function getConfig()
	{	
		$icons = [
			'mgz-oi mgz-oi-dial'              => 'Dial',
			'mgz-oi mgz-oi-pilcrow'           => 'Pilcrow',
			'mgz-oi mgz-oi-at'                => 'At',
			'mgz-oi mgz-oi-hash'              => 'Hash',
			'mgz-oi mgz-oi-key-inv'           => 'Key-inv',
			'mgz-oi mgz-oi-key'               => 'Key',
			'mgz-oi mgz-oi-chart-pie-alt'     => 'Chart-pie-alt',
			'mgz-oi mgz-oi-chart-pie'         => 'Chart-pie',
			'mgz-oi mgz-oi-chart-bar'         => 'Chart-bar',
			'mgz-oi mgz-oi-umbrella'          => 'Umbrella',
			'mgz-oi mgz-oi-moon-inv'          => 'Moon-inv',
			'mgz-oi mgz-oi-mobile'            => 'Mobile',
			'mgz-oi mgz-oi-cd'                => 'Cd',
			'mgz-oi mgz-oi-split'             => 'Split',
			'mgz-oi mgz-oi-exchange'          => 'Exchange',
			'mgz-oi mgz-oi-block'             => 'Block',
			'mgz-oi mgz-oi-resize-full'       => 'Resize-full',
			'mgz-oi mgz-oi-article-alt'       => 'Article-alt',
			'mgz-oi mgz-oi-article'           => 'Article',
			'mgz-oi mgz-oi-pencil-alt'        => 'Pencil-alt',
			'mgz-oi mgz-oi-undo'              => 'Undo',
			'mgz-oi mgz-oi-attach'            => 'Attach',
			'mgz-oi mgz-oi-link'              => 'Link',
			'mgz-oi mgz-oi-search'            => 'Search',
			'mgz-oi mgz-oi-mail'              => 'Mail',
			'mgz-oi mgz-oi-heart'             => 'Heart',
			'mgz-oi mgz-oi-comment'           => 'Comment',
			'mgz-oi mgz-oi-resize-full-alt'   => 'Resize-full-alt',
			'mgz-oi mgz-oi-lock'              => 'Lock',
			'mgz-oi mgz-oi-book-open'         => 'Book-open',
			'mgz-oi mgz-oi-arrow-curved'      => 'Arrow-curved',
			'mgz-oi mgz-oi-equalizer'         => 'Equalizer',
			'mgz-oi mgz-oi-heart-empty'       => 'Heart-empty',
			'mgz-oi mgz-oi-lock-empty'        => 'Lock-empty',
			'mgz-oi mgz-oi-comment-inv'       => 'Comment-inv',
			'mgz-oi mgz-oi-folder'            => 'Folder',
			'mgz-oi mgz-oi-resize-small'      => 'Resize-small',
			'mgz-oi mgz-oi-play'              => 'Play',
			'mgz-oi mgz-oi-cursor'            => 'Cursor',
			'mgz-oi mgz-oi-aperture'          => 'Aperture',
			'mgz-oi mgz-oi-play-circle2'      => 'Play-circle2',
			'mgz-oi mgz-oi-resize-small-alt'  => 'Resize-small-alt',
			'mgz-oi mgz-oi-folder-empty'      => 'Folder-empty',
			'mgz-oi mgz-oi-comment-alt'       => 'Comment-alt',
			'mgz-oi mgz-oi-lock-open'         => 'Lock-open',
			'mgz-oi mgz-oi-star'              => 'Star',
			'mgz-oi mgz-oi-user'              => 'User',
			'mgz-oi mgz-oi-lock-open-empty'   => 'Lock-open-empty',
			'mgz-oi mgz-oi-box'               => 'Box',
			'mgz-oi mgz-oi-resize-vertical'   => 'Resize-vertical',
			'mgz-oi mgz-oi-stop'              => 'Stop',
			'mgz-oi mgz-oi-aperture-alt'      => 'Aperture-alt',
			'mgz-oi mgz-oi-book'              => 'Book',
			'mgz-oi mgz-oi-steering-wheel'    => 'Steering-wheel',
			'mgz-oi mgz-oi-pause'             => 'Pause',
			'mgz-oi mgz-oi-to-start'          => 'To-start',
			'mgz-oi mgz-oi-move'              => 'Move',
			'mgz-oi mgz-oi-resize-horizontal' => 'Resize-horizontal',
			'mgz-oi mgz-oi-rss-alt'           => 'Rss-alt',
			'mgz-oi mgz-oi-comment-alt2'      => 'Comment-alt2',
			'mgz-oi mgz-oi-rss'               => 'Rss',
			'mgz-oi mgz-oi-comment-inv-alt'   => 'Comment-inv-alt',
			'mgz-oi mgz-oi-comment-inv-alt2'  => 'Comment-inv-alt2',
			'mgz-oi mgz-oi-eye'               => 'Eye',
			'mgz-oi mgz-oi-pin'               => 'Pin',
			'mgz-oi mgz-oi-video'             => 'Video',
			'mgz-oi mgz-oi-picture'           => 'Picture',
			'mgz-oi mgz-oi-camera'            => 'Camera',
			'mgz-oi mgz-oi-tag'               => 'Tag',
			'mgz-oi mgz-oi-chat'              => 'Chat',
			'mgz-oi mgz-oi-cog'               => 'Cog',
			'mgz-oi mgz-oi-popup'             => 'Popup',
			'mgz-oi mgz-oi-to-end'            => 'To-end',
			'mgz-oi mgz-oi-book-alt'          => 'Book-alt',
			'mgz-oi mgz-oi-brush'             => 'Brush',
			'mgz-oi mgz-oi-eject'             => 'Eject',
			'mgz-oi mgz-oi-down'              => 'Down',
			'mgz-oi mgz-oi-wrench'            => 'Wrench',
			'mgz-oi mgz-oi-chat-inv'          => 'Chat-inv',
			'mgz-oi mgz-oi-tag-empty'         => 'Tag-empty',
			'mgz-oi mgz-oi-ok'                => 'Ok',
			'mgz-oi mgz-oi-ok-circle'         => 'Ok-circle',
			'mgz-oi mgz-oi-download'          => 'Download',
			'mgz-oi mgz-oi-location'          => 'Location',
			'mgz-oi mgz-oi-share'             => 'Share',
			'mgz-oi mgz-oi-left'              => 'Left',
			'mgz-oi mgz-oi-target'            => 'Target',
			'mgz-oi mgz-oi-brush-alt'         => 'Brush-alt',
			'mgz-oi mgz-oi-cancel'            => 'Cancel',
			'mgz-oi mgz-oi-upload'            => 'Upload',
			'mgz-oi mgz-oi-location-inv'      => 'Location-inv',
			'mgz-oi mgz-oi-calendar'          => 'Calendar',
			'mgz-oi mgz-oi-right'             => 'Right',
			'mgz-oi mgz-oi-signal'            => 'Signal',
			'mgz-oi mgz-oi-eyedropper'        => 'Eyedropper',
			'mgz-oi mgz-oi-layers'            => 'Layers',
			'mgz-oi mgz-oi-award'             => 'Award',
			'mgz-oi mgz-oi-up'                => 'Up',
			'mgz-oi mgz-oi-calendar-inv'      => 'Calendar-inv',
			'mgz-oi mgz-oi-location-alt'      => 'Location-alt',
			'mgz-oi mgz-oi-download-cloud'    => 'Download-cloud',
			'mgz-oi mgz-oi-cancel-circle'     => 'Cancel-circle',
			'mgz-oi mgz-oi-plus'              => 'Plus',
			'mgz-oi mgz-oi-upload-cloud'      => 'Upload-cloud',
			'mgz-oi mgz-oi-compass'           => 'Compass',
			'mgz-oi mgz-oi-calendar-alt'      => 'Calendar-alt',
			'mgz-oi mgz-oi-down-circle'       => 'Down-circle',
			'mgz-oi mgz-oi-award-empty'       => 'Award-empty',
			'mgz-oi mgz-oi-layers-alt'        => 'Layers-alt',
			'mgz-oi mgz-oi-sun'               => 'Sun',
			'mgz-oi mgz-oi-list'              => 'List',
			'mgz-oi mgz-oi-left-circle'       => 'Left-circle',
			'mgz-oi mgz-oi-mic'               => 'Mic',
			'mgz-oi mgz-oi-trash'             => 'Trash',
			'mgz-oi mgz-oi-quote-left'        => 'Quote-left',
			'mgz-oi mgz-oi-plus-circle'       => 'Plus-circle',
			'mgz-oi mgz-oi-minus'             => 'Minus',
			'mgz-oi mgz-oi-quote-right'       => 'Quote-right',
			'mgz-oi mgz-oi-trash-empty'       => 'Trash-empty',
			'mgz-oi mgz-oi-volume-off'        => 'Volume-off',
			'mgz-oi mgz-oi-right-circle'      => 'Right-circle',
			'mgz-oi mgz-oi-list-nested'       => 'List-nested',
			'mgz-oi mgz-oi-sun-inv'           => 'Sun-inv',
			'mgz-oi mgz-oi-bat-empty'         => 'Bat-empty',
			'mgz-oi mgz-oi-up-circle'         => 'Up-circle',
			'mgz-oi mgz-oi-volume-up'         => 'Volume-up',
			'mgz-oi mgz-oi-doc'               => 'Doc',
			'mgz-oi mgz-oi-quote-left-alt'    => 'Quote-left-alt',
			'mgz-oi mgz-oi-minus-circle'      => 'Minus-circle',
			'mgz-oi mgz-oi-cloud'             => 'Cloud',
			'mgz-oi mgz-oi-rain'              => 'Rain',
			'mgz-oi mgz-oi-bat-half'          => 'Bat-half',
			'mgz-oi mgz-oi-cw'                => 'Cw',
			'mgz-oi mgz-oi-headphones'        => 'Headphones',
			'mgz-oi mgz-oi-doc-inv'           => 'Doc-inv',
			'mgz-oi mgz-oi-quote-right-alt'   => 'Quote-right-alt',
			'mgz-oi mgz-oi-help'              => 'Help',
			'mgz-oi mgz-oi-info'              => 'Info',
			'mgz-oi mgz-oi-pencil'            => 'Pencil',
			'mgz-oi mgz-oi-doc-alt'           => 'Doc-alt',
			'mgz-oi mgz-oi-clock'             => 'Clock',
			'mgz-oi mgz-oi-loop'              => 'Loop',
			'mgz-oi mgz-oi-bat-full'          => 'Bat-full',
			'mgz-oi mgz-oi-flash'             => 'Flash',
			'mgz-oi mgz-oi-moon'              => 'Moon',
			'mgz-oi mgz-oi-bat-charge'        => 'Bat-charge',
			'mgz-oi mgz-oi-loop-alt'          => 'Loop-alt',
			'mgz-oi mgz-oi-lamp'              => 'Lamp',
			'mgz-oi mgz-oi-doc-inv-alt'       => 'Doc-inv-alt',
			'mgz-oi mgz-oi-pencil-neg'        => 'Pencil-neg',
			'mgz-oi mgz-oi-home'              => 'Home'
		];

		$options = [];
		foreach ($icons as $value => $label) {
			$options[] = [
				'label' => $label,
				'value' => $value
			];
		}

		return $options;
	}
}