<?php
/** @var \WeltPixel\QuickCart\Block\CarouselContent $block */
/** @var \Magento\Catalog\Block\Product\AbstractProduct $productViewModel */

$productViewModel = $block->getProductViewModel();
$image = 'related_products_list';
$carouselProducts = $block->getCarouselProducts();
$carouselTitle = $block->getCarouselTitle();
$carouselTitleAlignment = $block->getCarouselTitleAlignment();
$carouselItemMobile = $block->getCarouselItemMobile();
$carouselItemDesktop = $block->getCarouselItemDesktop();
?>
<?php if ($carouselProducts && $carouselProducts->getSize()) : ?>
<?php $items = $carouselProducts->getItems(); ?>
    <div class="quickcart-carousel-products-wrapper">
        <?php if ($carouselTitle) : ?>
            <div class="quickcart-carosuel-title <?= $carouselTitleAlignment ?>"><?= $carouselTitle ?></div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items owl-quickcart-carousel-products-popup">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info">
                        <a href="<?php /* @escapeNotVerified */ echo $productViewModel->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php echo $productViewModel->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $productViewModel->getProductUrl($_item) ?>">
                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                            <?php /* @escapeNotVerified */ echo $productViewModel->getProductPrice($_item); ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
            <div id="pre-div">
                <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
                <?php if ($loaderHelper->useDefaultLoader() ) : ?>
                    <div class="cssload-loader">
                        <div class="cssload-inner cssload-one"></div>
                        <div class="cssload-inner cssload-two"></div>
                        <div class="cssload-inner cssload-three"></div>
                    </div>
                <?php else : ?>
                    <table class="imageloader-loader">
                        <tbody>
                        <tr>
                            <td>
                                <img src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                            </td>
                        </tr>
                        </tbody>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php
    try {
        /* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
        $helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
        $breakpoint = $helperCustom->getBreakpointConfiguration();
        $sliderPrevLabel = 'prev';
        $sliderNextLabel = 'next';
        $sliderNavPrevClass = 'owl-prev';
        $sliderNavNextClass = 'owl-next';
    } catch (\Exception $ex) {}
    ?>
    <script>
        require(['jquery', 'owl_carousel', 'owl_config' ],
            function ($) {
                $(document).ready(function() {
                    var carouselElement = $('.owl-quickcart-carousel-products-popup'),
                        windowWidth = $(window).width(),
                        carouselWidth = carouselElement.width(),
                        carouselContainer = carouselWidth + 120,
                        items = <?= $carouselItemDesktop ?>,
                        stagePadding =  0,
                        sPBrk_1 = 0,
                        sPBrk_2 = 0,
                        sPBrk_3 = 0,
                        sPBrk_4 = 0,
                        rtl = false,
                        navClass = [ '<?= $sliderNavPrevClass ?>', '<?= $sliderNavNextClass ?>' ],
                        navText = [ '<?= $sliderPrevLabel ?>', '<?= $sliderNextLabel ?>' ];

                    if (rtl) {
                        navClass = navClass.reverse();
                        navText = navText.reverse();
                    }

                    /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                    carouselElement.on('initialized.owl.carousel', function(event){
                        var scopeSize = event.page.size,
                            navBtnL = carouselElement.find('.owl-prev'),
                            navBtnR = carouselElement.find('.owl-next');

                        if(event.item.count <= event.page.size) {
                            navBtnL.css('display', 'none');
                            navBtnR.css('display', 'none');
                        }

                        for (var i = 0; i < scopeSize; i++){
                            var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                            $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                            $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                        }
                        setTimeout(function(){
                            $('.owl-thumbs').each(function() {
                                if (!$('.owl-thumbs').children().length) {$(this).remove();}
                            });
                        }, 370);
                    });

                    carouselElement.on('initialized.owl.carousel', function(event) {
                        setTimeout(function(){
                            carouselElement.trigger('next.owl.carousel');
                            carouselElement.trigger('prev.owl.carousel');
                            $('.owl-thumbs').each(function() {
                                if (!$('.owl-thumbs').children().length) {$(this).remove();}
                            });
                            $('.cssload-loader').parent().remove();
                        }, 370);
                    });

                    carouselElement.owlCarousel({
                        nav                 : true,
                        navClass            :navClass,
                        navText             :navText,
                        dots                :false,
                        dotsEach            :false,
                        center              :false,
                        items               :items,
                        loop                :false,
                        margin              :0,
                        stagePadding        :stagePadding,
                        lazyLoad            :false,
                        autoplay            :false,
                        autoplayTimeout     :3000,
                        autoplayHoverPause  :false,
                        navSpeed            :0,
                        dotsSpeed           :0,
                        rtl                 :rtl,
                        autoHeight          :false,
                        slideBy             :'1',


                        responsive:{
                    <?php echo $breakpoint['breakpoint_1']; ?>:{
                            nav             :true,
                            dots            :false,
                            dotsEach        :false,
                            items           :<?= $carouselItemMobile ?>,
                            center          :false,
                            stagePadding    :sPBrk_1
                    },
                    <?php echo $breakpoint['breakpoint_2']; ?>:{
                            nav             :true,
                            dots            :false,
                            dotsEach        :false,
                            items           :<?= $carouselItemDesktop ?>,
                            center          :false,
                            stagePadding    :sPBrk_2
                    },
                    <?php echo $breakpoint['breakpoint_3']; ?>:{
                            nav             :true,
                            dots            :false,
                            dotsEach        :false,
                            items           :<?= $carouselItemDesktop ?>,
                            center          :false,
                            stagePadding    :sPBrk_3
                    },
                    <?php echo $breakpoint['breakpoint_4']; ?>:{
                            nav             :true,
                            dots            :false,
                            dotsEach        :false,
                            items           :<?= $carouselItemDesktop ?>,
                            center          :false,
                            stagePadding    :sPBrk_4
                    }
                }
                });

                    carouselElement.on('initialized.owl.carousel', function(event){
                        navBtnL = carouselElement.find('.owl-prev'),
                            navBtnR = carouselElement.find('.owl-next');

                        if(event.item.count <= event.page.size) {
                            navBtnL.css('display', 'none');
                            navBtnR.css('display', 'none');
                        }
                    });

                });
            });
    </script>
<?php endif; ?>
