<?php
/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <?php $_totalLabel = ($_total->getLabel() == 'Subtotal') ? 'Item Total' : $_total->getLabel();?>
        <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml($_totalLabel) ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml($_totalLabel) ?>
                <?php endif ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                <?php else : ?>
                    <?= /* @noEscape */ $block->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach?>
