<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<?php $product = $block->getProduct(); ?>

<?php if($product->getWmflatrate()): ?>
    <span class="flat-rate-info">
        <?= $block->escapeHtml(__('Oversized shipping charge: Ships for $%1', $product->getWmflatrate())) ?>
    </span>
<?php elseif ($product->getPsflatrate()): ?>
    <span class="flat-rate-info">
        <?= $block->escapeHtml(__('Oversized shipping charge: Ships for $%1', $product->getPsflatrate())) ?>
    </span>
<?php endif; ?>
