<?php
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>

<script type="text/javascript">
    require([
        'jquery',
        'mage/gallery/gallery'
        ], function($, gallery) {
            'use strict';

            $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {

                var galleryItem = '.fotorama-item';

                var zonosSelector = '.z-flag',
                    purechatSelector = '#purechat-container';

                $(galleryItem).on('fotorama:fullscreenexit',function () {
                    $(zonosSelector).css({'display':'block'});
                    $(purechatSelector).css({'display':'inline-block'});                    
                });   


                $(galleryItem).on('fotorama:fullscreenenter',function () {
                    $(zonosSelector).css({'display':'none'});
                    $(purechatSelector).css({'display':'none'}); 
                })
            });
        }
    );
</script>
