<div class="product-price <?php if($this->getTierPrices()){ echo 'has-tiers';} ?>">
    <div class="price-box">
        <?php echo $this->getPriceHtml(); ?>
        <?php echo $this->getProduct()->getMinimalPrice(); ?>
        <?php if($prices = $this->getTierPrices()){ ?>
            <div class="tier-price-wrapper">
                <?php echo $this->getTierPriceHtml(); ?>
            </div>
        <?php } ?>
    </div>
</div>


<style>
    .price-label {
        font-size:0.6em;
    }
    .price-wrapper {
        width:100%;
    }
    .price-excluding-tax {
        font-size:0.6em;
    }
    .price-label-ex-tax {
        font-size: 0.8em;
    }
    .no-display {
        display:none;
    }
</style>
