<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->getItem()->getProduct()->getTypeId() != 'appointment') : ?>
    <?php if ($block->isProductVisibleInSiteVisibility()): ?>
        <a class="action action-edit"
           href="<?= /* @escapeNotVerified */
           $block->getConfigureUrl() ?>"
           title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
            <span><?= /* @escapeNotVerified */
                __('Edit') ?></span>
        </a>
    <?php endif ?>
<?php endif ?>