<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$_helper = $this->helper('WeltPixel\QuickCart\Helper\Data');

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '<span class="wp-qcart-custom-msg" id="shoppingcart-custom-msg">'
        . $_helper->getShoppingCartMessageContentForDisplay()
        . '</span>'
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
    <div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
        <h1 class="page-title"
            <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()) : ?>
                aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
            <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
<style>
    .wp-qcart-custom-msg,
    .wp-qcart-custom-msg span {
        color:<?php echo $_helper->getShoppingCartMessageTextColor() ?>;
        font-size:<?php echo $_helper->getShoppingCartMessageFontSize() ?>;
    }
    <?php $customCss = $_helper->getShoppingCartMessageCustomCss(); ?>
    <?php if (strlen($customCss)): ?>
    <?php echo $customCss; ?>
    <?php endif; ?>
</style>
