<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="b2blink success message">
    <p><?= $block->escapeHtmlAttr(__('Registering a school, company, or organization?')) ?>
        <a href="/company_customer/account/create" title="<?= $block->escapeHtmlAttr(__('Create New Company Customer Account')) ?>"><?= $block->escapeHtmlAttr(__('Click Here')) ?></a>
    </p>
</div>
