<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Customer\Block\Account\RegisterLink */ ?>
<?php if (!$block->getLayout()->isBlock('register.customer.link')) : ?>
    <li class="<?= $block->escapeHtml($block->getClass()) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?> >
            <?= $block->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>
