<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Appointment
 * @author      CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

$bannerImage = $block->getConfigBanner();
$params = $this->getRequest()->getParams();
$bookingImageHelper = $this->helper('Ced\Booking\Helper\Image');
$bookingDatahelper = $this->helper('Ced\Booking\Helper\Data');
$bannerImageWidth = $bookingDatahelper->getStoreConfig('booking/appointment_config/banner_width');
$bannerImageHeight = $bookingDatahelper->getStoreConfig('booking/appointment_config/banner_height');
$placeholder = $block->getViewFileUrl('Magento_Catalog::images/product/placeholder/image.jpg');
$width = $bannerImageWidth != ''? $bannerImageWidth : 800;
$height= $bannerImageHeight != ''? $bannerImageHeight : 200;

?>

<div class="ced-appointment-banner-wrapper">
    <img id="appointment-banner"
         src="<?= $bookingImageHelper->resize($bannerImage,$width,$height,$placeholder);  ?>"
         alt="<?= __('Appointment Banner'); ?>" height="100%" width="100%" />
</div>

<?php /** code for listing of the products **/ ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('There are no products for this booking.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'list';
    $image = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="appointment-content-wrapper products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <?php $width = 135; $height = 135; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info clearfix" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php if ($_product->getBookingLocation()) : ?>
                        <div class="booking-location">
                            <strong class="distance location-li">
                                        <i class="fa fa-map-marker-alt" aria-hidden="true"></i>
                                        <a target="_blank"
                                           href="https://www.google.com/maps/place/<?= urlencode($_product->getBookingLocation()) ?>"><?= $_product->getBookingLocation(); ?></a>
                            </strong>
                        </div>
                        <?php endif; ?>
                        <div class="booking-facilities">
                            <?php $facilities = $this->helper('Ced\Booking\Helper\Data')->getProductFacilities($_product); ?>
                            <?php if ($facilities) : ?>
                                <?php foreach ($facilities as $facility) : ?>
                                    <?php $facilityhtml = '';
                                    switch ($facility->getImageType()) :
                                        case 'image' :  $facilityhtml = '<img title="'.$facility->getTitle().'" width="50px"
                                                               src="'.$this->helper('Ced\Booking\Helper\Data')->getImageUrl($facility->getImageValue()).'"
                                                               alt="'.$facility->getTitle().'">';
                                                     break;
                                        case 'icon'  : $facilityhtml = '<i title="'.$facility->getTitle().'"
                                                             class="ace-icon '.$facility->getImageValue().' fa-2x"></i>';
                                                     break;
                                    endswitch;
                                    echo $facilityhtml;
                                    ?>
                                <?php endforeach;?>
                            <?php endif;?>
                        </div>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="book-now-btn">
                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?= $block->getBlockHtml('formkey')?>
                                    <?php if (count($params)!=0 && isset($params['check_in'])) { ?>
                                        <button onclick="setLocation('<?= $_product->getProductUrl().'/?check_in='.$params['check_in'].'&check_out='.$params['check_out']; ?>')" type="submit"
                                                title="<?= $block->escapeHtml(__('Book Now')); ?>"
                                                class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Book Now') ?></span>
                                        </button>
                                    <?php } else { ?>
                                        <button onclick="setLocation('<?= $_product->getProductUrl() ?>')" type="submit"
                                                title="<?= $block->escapeHtml(__('Book Now')); ?>"
                                                class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Book Now') ?></span>
                                        </button>
                                    <?php } ?>
                                <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?=($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    function setLocation(url){
        window.location.href = url;
    }
</script>




