<?php
/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>

<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    
<?php 
    $isAdded = false;
    $_product = $block->getProduct();
    $_wishlistCollection = $this->helper('Magento\Wishlist\Helper\Data')->getWishlistItemCollection();
    foreach ($_wishlistCollection as $_item) {
        $__product = $_item->getProduct();
        if ($_product->getId() == $__product->getId()) {
            $isAdded = true;
            break;
        }
    }
?>

<?php if($isAdded): ?>
    <a href="javascript:void(0)"
            class="action towishlist towishlist--added"
            title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
            aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
            data-action="add-to-wishlist"
            role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>       
    <?php else: ?>
        <a href="#"
            class="action towishlist"
            title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
            aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
            data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
            data-action="add-to-wishlist"
            role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>        
    <?php endif; ?>    
<?php endif; ?>
