<?php

// Mage::app();

// $isActive = Mage::getStoreConfig("clearsale_total/general/active");

// $apikey = Mage::getStoreConfig("clearsale_total/general/key");


// if ($isActive) 
// {
    
    // if(isset($_GET["apikey"]))
    // {
    
     // if($apikey == $_GET["apikey"])
     // {
		 // if($_GET["action"])
		 // {
			 // $obj = Mage::getModel('integration/observer');
			 // $action =  $_GET["action"];
		    // if($action == 'get')
			// {
			 // echo "Buscar<br />";	
			 // $obj->getClearsaleOrderStatus();
			// }else if($action= 'send')
			// {
			 // echo "Enviar<br />";
			 // $obj->sendPendingOrders();
			// }

          // echo "OK";
		 // }
     // }
    // }
// }

?>