<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<span id="see-more-additional-content" class="additional-content-link">
    <span><?= $escaper->escapeHtml(__('See More')) ?></span>
</span>

<div id="amstockstatus-additional-content" class="additional-content-popup">
    <div class="modal-body-content" style="display: none">
        <p><?= $escaper->escapeHtml($block->getData('additional_content')) ?></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal",
        "mage/translate"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: $.mage.__('Check availability'),
            modalClass: 'stock-status-popup',
            buttons: [{
                text: $.mage.__('Close'),
                class: 'stock-status-popup-button',
                click: function () {
                    this.closeModal();
                }
            }]
        };
        var popup = modal(options, $('#amstockstatus-additional-content'));
        $(".additional-content-link").click(function() {
            $('.modal-body-content').show();
            $('#amstockstatus-additional-content').modal('openModal');
        });
    });
</script>
