<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Squiz.PHP.GlobalKeyword.NotAllowed
?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $this->helper(\Magento\Tax\Helper\Data::class)->getCalculatedTaxes($_source);
    global $taxIter;
    $taxIter++;
?>


<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary plane">
<?php else : ?>
<tr class="totals-tax">
<?php endif; ?>
    <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
        <?php if ($block->displayFullSummary()) : ?>
            <div class="detailed"><?= $block->escapeHtml(__('Tax')) ?></div>
        <?php else : ?>
            <?= $block->escapeHtml(__('Tax')) ?>
        <?php endif; ?>
    </th>
    <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr(__('Tax')) ?>">
        <?= /* @noEscape */ $_order->formatPrice($_source->getTaxAmount()) ?>
    </td>
</tr>
