<?php if ($this->getApiModel()->getClient() && $this->getApiModel()->getClient()->isAccessTokenExpired()):?>
    <a class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="<?php echo $this->getApiModel()->getClient()->createAuthUrl()?>">
        <?php echo __("Sign in to Google (Deprecated)"); ?>
    </a>
    <p class="note">
        <span>
            <b><?php echo __("Note"); ?></b>:</b>
            <?php echo __('You can use the Json Export Option from below. More details: <a target="_blank" href="%1">here</a>', 'https://support.weltpixel.com/hc/en-us/articles/360012551019-Google-Tag-Manager-Sign-in-with-Google-temporarily-disabled-for-this-app') ?>
        </span>
    </p>
<?php else: ?>
<div>
    <?php echo __("<p>Please click <b>Save Config</b> button to save the entered API data, otherwise they will be lost</p>"); ?>
    <br/>
    <?php echo __("and <b>specify the GTM API credentials in the previous section!</b>"); ?>
    <hr/><br/>
    <?php echo __("<p><b>Create or Update Google AdWords conversion tracking automatically in Google Tag Manager.</b></p>"); ?>
    <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="api_form_key" id="api_form_key" />
    <hr/>
    <button id="save_gtm_api_conversion_tracking" title="<?php echo __("Setup Create AdWords conversion tracking");?>" type="button" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
        <span class="ui-button-text"><span><?php echo __("Setup AdWords conversion tracking"); ?></span></span>
    </button>
</div>
<script>
    requirejs(['jquery', 'WeltPixel_GoogleTagManager/js/gtmApi' ],
        function   ($, gtmApi) {
            $(document).ready(function() {
                gtmApi.initializeConversionTracking('<?php echo $this->getUrlForItemsCreation() ?>');
            });
        });
</script>
<?php endif; ?>
