<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Booking
 * @author      CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php $_product = $block->getProduct();  ?>
<?php $bookingTypes = $this->helper(\Ced\Booking\Helper\Data::class)->getEnabledBookingTypes(); ?>
<?php $mapApiKey = $this->helper(\Ced\Booking\Helper\Data::class)->getStoreConfig(\Ced\Booking\Helper\Data::XML_PATH_MAP_API_KEY); ?>

<?php if ($this->helper(\Ced\Booking\Helper\Data::class)->getStoreConfig('booking/booking_config/enable')) :  ?>

    <?php if ($_product->getBookingLocation() && in_array($_product->getTypeId(),$bookingTypes)) : ?>
        <script src="//maps.googleapis.com/maps/api/js?key=<?= $mapApiKey ?>&libraries=places"></script>
        <?php $location = $_product->getBookingLocation();  ?>

        <?php /**********************Map for Booking Product********************/ ?>
        <script>

            function initMap() {

                var defaultZoom = 10;

                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({'address': "<?= $location; ?>" }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {

                        lat = parseFloat(results[0].geometry.location.lat());
                        lon = parseFloat(results[0].geometry.location.lng());

                    } else {
                        lat = 22.08672;
                        lon = 79.42444;
                    }

                    var lat_lng = {lat: lat, lng: lon};
                    map = new google.maps.Map(document.getElementById('ced-booking-map'), {
                        zoom: defaultZoom,
                        center: lat_lng,
                    });

                    contentString = '<div><?= $location; ?></div>';

                    var infowindow = new google.maps.InfoWindow({
                        content: contentString
                    });


                    var marker = new google.maps.Marker({
                        position: lat_lng,
                        map: map
                    });
                    marker.addListener('click', function () {
                        infowindow.open(map, marker);
                    });
                });
            }
            google.maps.event.addDomListener(window, 'load', initMap);
        </script>
        <div id="ced-booking-map" style="width:100%;height:500px"></div>
    <?php endif; ?>
<?php endif; ?>
