<?php /** @var $block Amasty\Checkout\Block\Onepage\Success\Details */ ?>
<div class="account">
    <div class="column main">
        <div class="block block-order-details">
            <div class="block-title">
                <h2><?= $block->escapeHtml(__('Order details')) ?></h2>
            </div>
            <div class="order-date">
                <?= $block->escapeHtml(__('Order Date:')) ?> <?= $block->escapeHtml(
                    $block->formatDate(
                        $block->getOrder()->getCreatedAt(),
                        \IntlDateFormatter::LONG
                    )
                ) ?>
                <?= $block->getChildHtml('delivery') ?>
                <span class="delivery-date"><?= $block->escapeHtml($block->getDeliveryInfo()) ?></span>
            </div>
        </div>

        <?= $block->getChildHtml('info') ?>
        <?= $block->getChildHtml('comments') ?>
        <?= $block->getChildHtml('order_view') ?>
    </div>
</div>
