<?php
// @codingStandardsIgnoreFile
?>
<?php if ($this->isEnabled()) : ?>
    <?php $helper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data'); ?>
    <?php $product = $this->getCurrentProduct(); ?>
    <?php if (isset($product)) : ?>
        <?php $productDetails = []; ?>
        <?php

        $productDetail = [];
        $productDetail['name'] = html_entity_decode($product->getName());
        $productDetail['id'] = $helper->getGtmProductId($product);
        $productDetail['price'] = number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
        if ($helper->isBrandEnabled()) :
            $productDetail['brand'] = $helper->getGtmBrand($product);
        endif;
        $productDetail['category'] = $helper->getGtmCategoryFromCategoryIds($product->getCategoryIds());

        /** Set the custom dimensions */
        $customDimensions = $this->getProductDimensions($product, $helper);
        foreach ($customDimensions as $name => $value) :
            $productDetail[$name] = $value;
        endforeach;

        $productDetails['products'][] = $productDetail;
        ?>
        <?php
        $this->setEcommerceData('detail', $productDetails);
        $this->setEcommerceData('currencyCode', $this->getCurrencyCode());
        ?>

        <?php

        $relatedProductsCollection = $this->getRelatedProductCollection();
        $upsellProductsCollection = $this->getUpsellProductCollection();

        $productImpressions = [];

        if (count($relatedProductsCollection)) :
            $i = 1;
            foreach ($relatedProductsCollection as $_product) :
                $relatedProduct = [];
                $relatedProduct['name'] = html_entity_decode($_product->getName());
                $relatedProduct['id'] = $helper->getGtmProductId($_product);
                $relatedProduct['price'] = number_format($_product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
                if ($helper->isBrandEnabled()) :
                    $relatedProduct['brand'] = $helper->getGtmBrand($_product);
                endif;
                $relatedProduct['category'] = $helper->getGtmCategoryFromCategoryIds($_product->getCategoryIds());
                $relatedProduct['list'] = __('Related Products From') . ' ' . $product->getData('name');
                $relatedProduct['position'] = $i;
                $productImpressions[] = $relatedProduct;
                $i++;
            endforeach;
        endif;

        if (count($upsellProductsCollection)) :
            $i = 1;
            foreach ($upsellProductsCollection as $_product) :
                $upsellProduct = [];
                $upsellProduct['name'] = html_entity_decode($_product->getName());
                $upsellProduct['id'] = $helper->getGtmProductId($_product);
                $upsellProduct['price'] = number_format($_product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
                if ($helper->isBrandEnabled()) :
                    $upsellProduct['brand'] = $helper->getGtmBrand($_product);
                endif;
                $upsellProduct['category'] = $helper->getGtmCategoryFromCategoryIds($_product->getCategoryIds());
                $upsellProduct['list'] = __('Upsell Products From') . ' ' . $product->getData('name');
                $upsellProduct['position'] = $i;
                $productImpressions[] = $upsellProduct;
                $i++;
            endforeach;
        endif;

        if (count($productImpressions)) :
            $this->setEcommerceData('impressions', $productImpressions);
            $this->setDataLayerOption('event', 'impression');
            $this->setDataLayerOption('eventCategory', 'Ecommerce');
            $this->setDataLayerOption('eventAction', 'Impression');
            $this->setDataLayerOption('eventLabel', \WeltPixel\GoogleTagManager\Model\Api\Remarketing::ECOMM_PAGETYPE_PRODUCT . ' ' . html_entity_decode($_product->getName()));
        endif;

        if ($helper->isAdWordsRemarketingEnabled()):
            $remarketingData = [];
            $remarketingData['ecomm_pagetype'] = \WeltPixel\GoogleTagManager\Model\Api\Remarketing::ECOMM_PAGETYPE_PRODUCT;
            $remarketingData['ecomm_prodid'] = $helper->getGtmProductId($product);
            $remarketingData['ecomm_totalvalue'] = number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
            $remarketingData['ecomm_category'] = $helper->getGtmCategoryFromCategoryIds($product->getCategoryIds());
            $this->setDataLayerOption('google_tag_params', $remarketingData);
        endif;

        ?>

    <?php endif; ?>
<?php endif; ?>
